language: c
env:
  - OCAML_VERSION=4.08.0+rc2
cache:
  directories:
    - ${HOME}/.opam
before_install:
  - wget -O ${HOME}/opam https://github.com/ocaml/opam/releases/download/2.0.2/opam-2.0.2-x86_64-linux
  - chmod +x ${HOME}/opam
  - export PATH=${HOME}:${PATH}
  - export OPAMYES=1
  - export OPAMJOBS=2
  - opam init --bare --disable-sandboxing
  - opam repo add --dont-select beta https://github.com/ocaml/ocaml-beta-repository.git
  - opam switch create ${OCAML_VERSION} --repositories=default,beta
  - eval `opam config env`
  - export OPAMVERBOSE=1
install:
  - opam update --upgrade
  - opam pin add --no-action ocamlformat .
  - opam install --deps-only ocamlformat
script:
  - make test
  - opam install ocamlformat
