name: Test OCamlformat on other projects

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-branch:
    needs: build-linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile:
          - conventional
          - ocamlformat
          - janestreet
        include:
          - ocp_indent: true
            ocp_indent_config: JaneStreet
            profile: janestreet

    steps:
      - name: Install ocp-indent
        if: ${{ matrix.ocp_indent }}
        run: |
          sudo apt install -y ocp-indent
          sudo touch /etc/ocamlfind.conf

      # Clone the project
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch main build of ocamlformat
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-linux.yml
          workflow_conclusion: ""
          check_artifacts: true
          branch: main
          name: ocamlformat-${{ runner.os }}-${{ runner.arch }}
          path: ocamlformat-a

      - name: Fetch new build of ocamlformat
        uses: actions/download-artifact@v3
        with:
          name: ocamlformat-${{ runner.os }}-${{ runner.arch }}
          path: ocamlformat-b

      - name: Test ${{ matrix.profile }} profile
        run: |
          chmod +x ocamlformat-a/ocamlformat ocamlformat-b/ocamlformat
          ./tools/test_branch.sh $TEST_BRANCH_ARGS -n -a ocamlformat-a/ocamlformat -b ocamlformat-b/ocamlformat 'profile=${{ matrix.profile }}'
        shell: bash
        env:
          OCP_INDENT_CONFIG: ${{ matrix.ocp_indent_config }}
          TEST_BRANCH_ARGS: ${{ matrix.ocp_indent && '-o -s' || '' }}
