name: Test branch

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-branch:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile:
          - conventional
          - ocamlformat
          - janestreet

    steps:
      # Clone the project
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch main build of ocamlformat
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          branch: main
          name: ocamlformat-${{ matrix.platform.name }}-${{ matrix.platform.target_arch }}
          path: ocamlformat-a

      - name: Fetch new build of ocamlformat
        uses: actions/download-artifact@v3
        with:
          name: ocamlformat-${{ matrix.platform.name }}-${{ matrix.platform.target_arch }}
          path: ocamlformat-b

      - name: Test ${{ matrix.profile }} profile
        run: ./tools/test_branch.sh -n -a ocamlformat-a -b ocamlformat-b 'profile=${{ matrix.profile }}'
        shell: bash
